accounts/urls.py
from django.urls import path
from .views import LoginView,Register,LogoutView,verify,like_recipe,get_liked_recipes,editProfile,change_email,change_password,make_menu,blog

app_name = 'accounts'

urlpatterns = [
    path('login/',LoginView,name='login'),
    path('register/',Register,name='register'),
    path('logout/',LogoutView, name='logout'),
    path('verify/<slug>',verify,name='verify'),
    path('editprofile/',editProfile,name='edit_profile'),
    path('change_password/',change_password,name="change_password"),
    path('change_email/',change_email,name="change_email"),
    # path('check_email/',check_email,name="check_email"),
    path('make_menu/',make_menu, name="make_menu"),
    path("blog/", blog, name="blog"),
    path('like-recipe/',like_recipe, name="like_recipe"),
    path('liked_recipes/',get_liked_recipes, name="get_liked_recipes"),
    
]

home/urls.py
from django.urls import path
from .views import home,contact

app_name = 'home'

urlpatterns = [
    path('',home,name='home'),
    path("contact/",contact,name="contact")
]

receipes/urls.py
from django.urls import path
from .views import add_recipe,get_recipe

app_name = 'receipes'

urlpatterns = [
    path('add-recipe/',add_recipe,name='add_recipe'),
    path('<slug>',get_recipe,name="get_recipe"),
]

recipe/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path("", include('home.urls')),
    path('recipes/',include('receipes.urls')),
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from email import message
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager
from django.core.validators import MaxValueValidator,MinValueValidator
from helpers import generate_unique_hash
from receipes.models import Recipe

# Create your models here.
class CustomUser(AbstractUser):
    username = models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username',null=True, blank=True)
    email = models.EmailField(unique=True,max_length = 255)
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    user_image = models.ImageField(upload_to = 'images/user/',null=True, blank=True)
    phone_no = models.IntegerField(validators=[MaxValueValidator(999999999999),MinValueValidator(000000000000)],null=True, blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    temp_email = models.EmailField(null=True,blank=True,max_length = 255,default= None)
    forgot_password_token = models.SlugField(unique=True, null=True, blank=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()
    
    def name(self):
        return self.first_name +" "+ self.last_name
    
    def __str__(self) -> str:
        return self.email
    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_hash()
        super(CustomUser, self).save(*args, **kwargs)
        
        
class LikedRecipe(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="liked_recipes")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True,blank=True, related_name="liked_by")
    
    
    def __str__(self):
        return self.user.email + " liked " + self.recipe.recipe_name


    
class menu(models.Model):
    DAYS = [
    ("monday","Monday"),
    ("tuesday","Tuesday"),
    ("wednesday","Wednesday"),
    ("tursday","Trusday"),
    ("friday","Friday"),
    ("saturday","Saturday"),
    ("sunday","Sunday"),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="menu")
    day = models.CharField( max_length=50,choices= DAYS)
    breakfast = models.ForeignKey("receipes.Recipe", related_name='break_fast', on_delete=models.CASCADE)
    lunch = models.ForeignKey("receipes.Recipe", related_name='lunch', on_delete=models.CASCADE)
    dinner = models.ForeignKey("receipes.Recipe", related_name='dinner', on_delete=models.CASCADE)
    updated_at = models.DateField(auto_now=True)    
    

    def __str__(self) -> str:
        return self.user.email+ " - " + self.day
    
class Blog(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="blog")
    title = models.CharField( max_length=50)
    category = models.CharField( max_length=50)
    message = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_hash()
        super(Blog, self).save(*args, **kwargs)
        
    def __str__(self) -> str:
        return self.title
    
    

accounts/views.py
from django.http import JsonResponse,HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model,login,logout,authenticate
from helpers import send_email_token,generate_unique_hash
import json
from django.contrib import messages
from receipes.models import Recipe
from recipe import settings
from .models import LikedRecipe,menu,Blog

import receipes

User = get_user_model()

# Create your views here.
def LoginView(request):
    if request.user.is_authenticated:
        messages.success(request, "You are already logged in")
        return redirect('home:home')
    else:
        if request.method == "POST":
            try:
                # body = request.data
                body = request.POST
                print(body)
                if ('email' in body and 'password' in body):
                    email = body['email']
                    password = body['password']
                    
                    user_obj = User.objects.filter(email=email).first()
                    
                    if user_obj and not user_obj.is_superuser:
                        if not user_obj.is_verified:
                            raise Exception('You have to verify your mail through link sent to you by mail')
                        
                        user = authenticate(request=request, email=email, password=password)
                        if user:
                            login(request=request,user=user)
                            return redirect('home:home')
                        else:
                            raise Exception('Invalid Password!')
                    else:
                        raise Exception("No user with this email exists!")
                    
                else:
                    raise Exception('Provide proper credentials to login')
                    
            except Exception as e:
                messages.warning(request, str(e))
                return HttpResponseRedirect(request.path_info)
                # return JsonResponse({'success':False, 'message':str(e)})
            
        
        return render(request, 'accounts/login.html')
   
   

def Register(request):
    
    if request.user.is_authenticated:
        messages.success(request, "You are already logged in")
        return redirect('home:home')
    
    else:  
        if request.method == "POST":
            try:
                body = request.POST
                # body = request.data
                if ('email' in body and 'password' in body):
                    email = body['email']
                    password = body['password']
                    first_name = body['first_name']
                    phone_no = body['phone_no']
                    last_name = body['last_name']
                    user_image = request.FILES.get('user_image')
                    if user_image: 
                        if user_image.size > 1*1024*1024:
                            raise Exception('Image size should be less than 1MB')
                    
                    user, created = User.objects.get_or_create(email=email)
                    if created :
                        user.first_name = first_name
                        user.phone_no = phone_no
                        user.last_name = last_name
                        user.set_password(password)
                        user.user_image = user_image
                        
                        user.save()
                        email_sent = send_email_token(email, user.slug)
                        if email_sent: 
                            messages.success(request, "Verification mail is sent your email")
                            return HttpResponseRedirect(request.path_info)
                            # return JsonResponse({
                            #     'success':True,
                            #     'message':'Verification mail is sent your email'
                            # })
                        else:
                            raise Exception('There is some problem in sending mail')
                            # return JsonResponse({
                            #     'success':False,
                            #     'message':"There's some problem in sending mail"
                            # })
                        
                    else:
                        raise Exception('User with this email already exists')
                    
                else:
                    raise Exception('Provide proper credentials ')
            
            except Exception as e:
                messages.warning(request, str(e))
                return HttpResponseRedirect(request.path_info)
                # return JsonResponse({
                #     'status':False,
                #     'message':str(e)
                #     })
                
        return render(request, 'accounts/signup.html')

def verify(request, slug):
    try:
        user = User.objects.filter(slug=slug).first()
        if user:
            if user.is_verified :
                if user.temp_email != None:
                    user.email = user.temp_email
                    user.temp_email = None
                    user.save()
                    logout(request)
                    context = {
                        'success': True,
                        'message': 'New email set Successfully'
                    }
                    context_obj = { 'data':json.dumps(context)}
                    return render(request, 'accounts/verify.html', context_obj) 
                    
                context = {
                    'success': True,
                    'message': 'Your email is already verified. Youc can login'
                }
            
            user.is_verified = True
            user.save()
            context = {
                    'success': True,
                    'message': 'Your email is verified. You can login'
                }
        
        else:
            raise Exception('Invalid verification link!')
        
    except Exception as e:
        print(e)
        context = {
                    'success': False,
                    'message': str(e)
                }
    finally:
        context_json = json.dumps(context)
        context_obj = { 'data':context_json}
        return render(request, 'accounts/verify.html', context_obj) 
        

def LogoutView(request):
    logout(request)
    return redirect('accounts:login')


def like_recipe(request):
    
    if request.user.is_authenticated:
        try:
            if request.method == "GET":
                print(request.GET)
                if 'slug' in request.GET:
                    slug = request.GET['slug']
                    print(slug)
                    recipe = Recipe.objects.filter(slug=slug).first()
                    if recipe:  
                        liked_recipe, created = LikedRecipe.objects.get_or_create(user=request.user, recipe=recipe)
                        if created:
                            recipe.likes += 1
                            recipe.save()
                            return JsonResponse({'success':True,'message': 'Recipe liked successfully.','liked': True,'likes':recipe.likes})

                        else:
                            liked_recipe.delete()
                            recipe.likes -= 1
                            recipe.save()
                            return JsonResponse({'success':True,'message': 'Recipe removed from liked successfully.','liked': False,'likes':recipe.likes})
                    else:
                        raise Exception('There is some problem in recipe liking')
                    
                else:
                    raise Exception('Do not try to manipulate things')
                    
                   
                
        except Exception as e:
            print(e)
            messages.warning(request, str(e))
            return JsonResponse({'success':False,'message':str(e),'safe':False})
            
    else:
        messages.warning(request, "You need to login to like the recipes")
        return JsonResponse({'success':False,'message':'redirect','safe':False})
        
def get_liked_recipes(request):
    
    if request.user.is_authenticated:
    
        liked_recipes = LikedRecipe.objects.filter(user=request.user)
        
        context = {'liked_recipes': liked_recipes }
        return render(request, 'accounts/liked_recipes.html', context)
    
    else:
        messages.warning(request, "YOu need to login to like the recipes")
        return redirect('accounts:login')
    
    
def editProfile(request):
    if request.user.is_authenticated:
        
        if request.method == "POST":
            try:
                body = request.POST
                print(body)
                if 'first_name' in body and 'last_name' in body and 'email' in body and 'phone_no' in body:
                    user = request.user
                    if user.email == body['email']:
                        
                        user.first_name = body['first_name']
                        user.phone_no = body['phone_no']
                        user.last_name = body['last_name']
                       
                            
                        user.save() 
                        messages.success(request, "Profile updated successfully")
                        return HttpResponseRedirect(request.path_info)
                    else:
                        raise Exception('Do not try anything funny with email here')
                else:
                    raise Exception('Provide your all details to complete profile')
                    
            except Exception as e:
                messages.success(request, str(e))
                return HttpResponseRedirect(request.path_info)
            
        if request.method == "GET":
            # print(request.user.user_image.url)

templates/accounts/blog.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Liked Recipe{% endblock %}</title>
{% block body %}

<div class="blog-area section-padding-30-80">
    <div class="container">
        <a href="#" class="btn delicious-btn mt-30 mb-30 search-btn">Add More</a>
        <div class="search-wrapper">
            <!-- Close Btn -->
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="contact-form-area">
                            <form action="" method="post">{% csrf_token %}
                                <div class="row">
                                    <div class="col-12 col-lg-6">
                                        <input type="text" name="title" class="form-control" id="name" placeholder="Title">
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        <input type="category" name="category" class="form-control" id="category" placeholder="Category">
                                    </div>
                                    
                                    <div class="col-12">
                                        <textarea name="message" class="form-control" id="message" cols="30" rows="7" placeholder="Message"></textarea>
                                    </div>
                                    <div class="col-12 d-flex flex-wrap justify-content-between">
                                        <div><input type="submit" class="btn delicious-btn btn-3" value="Post"></div>
                                        
                                        <div class="close-btn"><i class="fa fa-times" ></i></div>
                                    </div>
                                    
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-12">
               

                <div class="blog-posts-area">
                    
                    <!-- Single Blog Area -->
                    {% for blog in blogs %}
                    
                    <div class="single-blog-area mb-4">
                        <!-- Thumbnail -->
                        <!-- Content -->
                        <div class="blog-content">
                            <a href="#" class="post-title">{{forloop.counter}}. {{blog.title}} - {{blog.category}}</a>
                            <div class="meta-data">by: <a href="#">{{blog.user.email}}</a> | on: <a href="#">{{blog.created_at}}</a>
                            </div>
                            <p>
                                {{blog.message}}
                            </p>
                            
                        </div>
                    </div>
                    
                    {% endfor %}

                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item active"><a class="page-link" href="#">01.</a></li>
                        <li class="page-item"><a class="page-link" href="#">02.</a></li>
                        <li class="page-item"><a class="page-link" href="#">03.</a></li>
                    </ul>
                </nav>
            </div>

            
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Edit Prfile {% endblock %}</title>
{% block body %}


<div class="col-12 mt-5">
    <div class="delicious-tabs-content">
        <ul class="nav nav-tabs d-flex justify-content-center" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active show" id="tab--1" data-toggle="tab" href="#tab1" role="tab" aria-controls="tab1" aria-selected="true">Edit Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="tab--2" data-toggle="tab" href="#tab2" role="tab" aria-controls="tab2" aria-selected="false">Change Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="tab--3" data-toggle="tab" href="#tab3" role="tab" aria-controls="tab3" aria-selected="false">Change Email</a>
            </li>
        </ul>

        <div class="tab-content mb-80" id="myTabContent">
            <div class="tab-pane fade active show" id="tab1" role="tabpanel" aria-labelledby="tab--1">
                <div class="delicious-tab-content">
                    <!-- Tab Text -->
                    {% comment %} edit profile {% endcomment %}
                    <div class="delicious-tab-text">
                        <div class="row">
                            <div class="col-12">
                                <div class="contact-form-area">
                                    <form  method="post" id="contact-form" autocomplete="off">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-12 col-lg-6">
                                                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name"
                                                value="{% if request.user.first_name %}{{request.user.first_name}}{% endif %}">
                                            </div>
                                            <div class="col-12 col-lg-6">
                                                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name"
                                                value="{% if request.user.last_name %}{{request.user.last_name}}{% endif %}">
                                            </div>
                                            <div class="col-12">
                                                <input type="number" class="form-control" id="phone_no" name="phone_no" value="{% if request.user.phone_no %}{{request.user.phone_no}}{%endif%}" placeholder="Phone No." required>
                                            </div>
                                            <div class="col-12">
                                                <input type="email" class="form-control" id="email" name="email"  value="{{request.user.email}}" readonly placeholder="E-mail" required>
                                            </div>
                                            <div class="col-12 text-center">
                                                <button class="btn delicious-btn mt-30" type="submit">Send</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="tab--2">
                <div class="delicious-tab-content">
                    <!-- Tab Text -->
                    {% comment %} change password {% endcomment %}
                    <div class="delicious-tab-text">
                        <div class="delicious-tab-text">
                            <div class="row">
                                <div class="col-12">
                                    <div class="contact-form-area">
                                        <form  method="post" id="password-change-form" autocomplete="off">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-12">
                                                    <input type="password" class="form-control" name="cur_password" id="cur_password" placeholder="Current Password." required>
                                                </div>
                                                <div class="col-12">
                                                    <input type="password" name="new_password" id="new_password" placeholder="New Password*" class="form-control"  required>
                                                </div>
                                                <div class="col-12">
                                                    <input  type="password" name="confirm_password" id="confirm_password" placeholder="Confirm Password*" class="form-control" required>
                                                </div>
                                                <div id="password-error" class="text-danger text-center col-12  "></div>
                                                <div class="col-12 text-center">
                                                    <button class="btn delicious-btn mt-30" type="submit">Update Password</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="tab--3">
                <div class="delicious-tab-content">
                    <!-- Tab Text -->
                    {% comment %} chnage email {% endcomment %}
                    <div class="delicious-tab-text">
                        <div class="delicious-tab-text">
                            <div class="delicious-tab-text">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="contact-form-area">
                                            <form  method="post" id="email-change-form" autocomplete="off">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-12">
                                                        <input type="email" name="cur_email" id="cur_email" placeholder="Current Email*" class="form-control" required value="{{request.user.email}}" readonly>
                                                    </div>
                                                    <div class="col-12">
                                                        <input type="email" name="new_email" id="new_email" placeholder="New Email*" class="form-control" required>
                                                    </div>
                                                   
                                                    <div class="col-12 text-center">
                                                        <button class="btn delicious-btn mt-30" type="submit">Update Email</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div> 
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}

<script>
    const form_pass = document.getElementById('password-change-form');
    const newPassword = document.getElementById('new_password');
    const confirmPassword = document.getElementById('confirm_password');
    const passwordError = document.getElementById('password-error');
    
    
    form_pass.addEventListener('submit', function (event) {
        event.preventDefault();
        if (newPassword.value !== confirmPassword.value) {
            passwordError.textContent = "Passwords do not match";
            
        } else {
            passwordError.textContent = ""; // Clear any previous error message
            // Check current password before submitting the form
            submitForm();
        }
    });


    function submitForm() {
        const formData = new FormData(form_pass)
        console.log(form_pass)
        fetch('{% url "accounts:change_password" %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        }).then(response => response.json())
        .then(data => {
            console.log(data)
            if (data.success) {
                // Handle success response here
                alert(data.message)
                window.location.href = "{% url 'accounts:login' %}";
                $('#chngpassmodal').modal('hide');
            } else {
                passwordError.textContent = data.message;
            }
        }).catch(error => {
            console.error("Network error occurred", error);
        });
    }
</script>

<script>
    const form_email = document.getElementById('email-change-form');
    form_email.addEventListener('submit', function (event) 
    {
        const formData = new FormData(form_email)
        console.log(formData)
        event.preventDefault();
        fetch('{% url "accounts:change_email" %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        }).then(response => response.json())
        .then(data => {
            console.log(data)
            if (data.success) {
                // Handle success response here
                alert(data.message)
                window.location.href = "{% url 'accounts:login' %}";
                $('#chngpassmodal').modal('hide');
            } else {
                event.preventDefault(); 
                passwordError.textContent = data.message;
            }
        }).catch(error => {
            console.error("Network error occurred", error);
        });
        
    });    
</script>


{% endblock %}

templates/accounts/verify.html
<script>
    {% comment %} function verifyEmail(slug) {
        fetch(`/verify/${slug}`)
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            const jsonData = JSON.parse('{{ json_data|escapejs }}');
            if (data.success) {
                alert(data.message);
                // Redirect to the login page
                window.location.href = '/login'; // Adjust the URL as per your project's setup
            } else {
                alert(data.message);
                window.location.href = '/register';
            }
        })
        .catch(error => {
            console.error('There was a problem with the fetch operation:', error);
            alert('An error occurred. Please try again later.');
        });
    } {% endcomment %}
    var jsonData = JSON.parse('{{ data|escapejs }}');
    if (jsonData.success) {
        alert(jsonData.message);
        // Redirect to the login page
        window.location.href = "{% url 'accounts:login' %}"; // Adjust the URL as per your project's setup
    } else {
        alert(jsonData.message);
        window.location.href =  "{% url 'accounts:register' %}";
    }
</script>
    