accounts/urls.py
from django.urls import path
from .views import LoginView,Register,LogoutView,verify,like_recipe,get_liked_recipes,editProfile,change_email,change_password,make_menu,blog

app_name = 'accounts'

urlpatterns = [
    path('login/',LoginView,name='login'),
    path('register/',Register,name='register'),
    path('logout/',LogoutView, name='logout'),
    path('verify/<slug>',verify,name='verify'),
    path('editprofile/',editProfile,name='edit_profile'),
    path('change_password/',change_password,name="change_password"),
    path('change_email/',change_email,name="change_email"),
    # path('check_email/',check_email,name="check_email"),
    path('make_menu/',make_menu, name="make_menu"),
    path("blog/", blog, name="blog"),
    path('like-recipe/',like_recipe, name="like_recipe"),
    path('liked_recipes/',get_liked_recipes, name="get_liked_recipes"),
    
]

home/urls.py
from django.urls import path
from .views import home,contact

app_name = 'home'

urlpatterns = [
    path('',home,name='home'),
    path("contact/",contact,name="contact")
]

receipes/urls.py
from django.urls import path
from .views import add_recipe,get_recipe

app_name = 'receipes'

urlpatterns = [
    path('add-recipe/',add_recipe,name='add_recipe'),
    path('<slug>',get_recipe,name="get_recipe"),
]

recipe/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path("", include('home.urls')),
    path('recipes/',include('receipes.urls')),
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from receipes.models import Recipe, Ingredients
from accounts.models import LikedRecipe
from helpers import send_Contact_mail
from django.contrib import messages
from django.http import HttpResponseRedirect

# Create your views here.
def home(request):

    recipes = Recipe.objects.all()
    if request.user.is_authenticated:
        liked_recipes = LikedRecipe.objects.filter(user=request.user).values_list('recipe')
    else:
        liked_recipes = None
        
    print(liked_recipes)
    context = {'recipes': recipes, 'liked_recipes':liked_recipes}
    print(context)
    return render(request, 'home.html',context)


def contact(request):
    
    if request.method == "POST":
        try:
            if request.user.is_authenticated:
                # body = request.data
                body = request.POST
                print(body)
                if ('name' in body and 'email' in body and 'phone_no' in body and 'subject' in body) :
                    if request.user.email == body['email']:
                        name = body['name']
                        email = body['email']
                        phone_no = body['phone_no']
                        subject = body['subject']
                        message = body['message']
                        
                        email_sent = send_Contact_mail(name,email,subject,message,phone_no)
                        if email_sent:
                            messages.success(request, "Email is sent")
                            return HttpResponseRedirect(request.path_info)
                        # return JsonResponse({
                            #     'success':True,
                            #     'message':'Email is sent'
                            # })
                        else:
                            raise Exception('Can not send the mail ')
                        
                    else:
                        raise Exception('Use the same email you logged in with.')
                        
                else:
                    raise Exception('Provide proper credentials')   
            else:
                raise Exception("You need to be logged in to send mail")
        except Exception as e:
            messages.warning(request, str(e))
            return HttpResponseRedirect(request.path_info)
            # return JsonResponse({'success':False, 'message':str(e)})
        
    return render(request,'contact.html')
 

templates/contact.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}LOGIN {% endblock %}</title>
{% block body %}

<div class="contact-area section-padding-0-80 mb-4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h3>Get In Touch</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="contact-form-area">
                    <form action="#" method="post">
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <input type="text" class="form-control" id="name" placeholder="Name">
                            </div>
                            <div class="col-12 col-lg-6">
                                <input type="email" class="form-control" id="email" placeholder="E-mail">
                            </div>
                            <div class="col-12">
                                <input type="number" class="form-control" id="subject" placeholder="Phone Number*">
                            </div>
                            <div class="col-12">
                                <input type="text" class="form-control" id="subject" placeholder="Subject">
                            </div>
                            <div class="col-12">
                                <textarea name="message" class="form-control" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn delicious-btn mt-30" type="submit">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}LOGIN - RECEIPE-NEST{% endblock %}</title>
{% block body %}

<section class="best-receipe-area">
    <div class="container">
        <div class="row">
            <div class="col-12 mt-3">
                <div class="section-heading">
                    <h3>The best Receipies</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Single Best Receipe Area -->
            {% for recipe in recipes %}
            <div class="col-12 col-sm-6 col-lg-4 text-center">
                <div class="single-best-receipe-area mb-30">
                    <div class="w-100 overflow-hidden" style="height: 250px; overflow:hidden;">
                        <a href="{% url 'receipes:get_recipe' recipe.slug%}"><img src="{{recipe.image.url}}" class="w-100 h-100" alt=""></a>
                    </div>
                    
                    <div class="receipe-content">
                        <a href="{% url 'receipes:get_recipe' recipe.slug%}">
                            <h5>{{recipe.recipe_name}}</h5>
                        </a>
                        <div class="ratings d-flex justify-content-around">
                            {% if request.user.is_authenticated %}
                                {% for liked in recipe.liked_by.all %}
                                    {% if liked.user == request.user %}
                                        <i class="heart-icon fa fa-heart" data-slug="{{ recipe.slug }}"></i>
                                    {% else %}
                                        {% if forloop.last %}
                                        <i class="heart-icon fa fa-heart-o" data-slug="{{ recipe.slug }}" aria-hidden="true"></i>
                                        {% endif %}
                                    {% endif %}
                                    {% empty %}
                                    <i class="heart-icon fa fa-heart-o" data-slug="{{ recipe.slug }}" aria-hidden="true"></i>
                                    {% endfor %}
                                    
                            {% else %}
                                <i class="heart-icon fa fa-heart-o" data-slug="{{ recipe.slug }}" aria-hidden="true"></i>
                            {% endif %}
                              
                                <span class="like-count">
                                    {% if recipe.likes %}
                                    {{recipe.likes}}
                                    {% else %}
                                    0
                                    {% endif %}
                                </span>
                           

                            <span>{{recipe.created_at}}</span>
                            
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

{% endblock %}

{% block script %}

<script>
    var path =  "{% url 'accounts:like_recipe' %}";
    var cur_path = "{{request.path}}"
    console.log(path);
</script>
<script src="{% static 'js/likerecipe.js' %}">  </script>

{% endblock %}